[package]
name = "spin-object-store"
version = "0.1.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
cap-std = "0.24.1"
serde = { version = "1.0", features = ["derive"] }
spin-engine = { path = "../engine" }
spin-manifest = { path = "../manifest" }
tracing = { version = "0.1", features = ["log"] }
wasmtime = "0.35"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "458a664bce7b2064d61fbd594efb2673d3130316" }