[package]
name = "spin-testing"
version = "0.1.0"
edition = "2021"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[dependencies]
anyhow = "1.0"
http = "0.2"
hyper = "0.14"
spin-engine = { path = "../engine" }
spin-manifest = { path = "../manifest" }
spin-http-engine = { path = "../http" }
spin-trigger = { path = "../trigger" }